server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  application:
    name: service-provider
  main:
      allow-bean-definition-overriding: true
mybatis:
  type-aliases-package: com.cloud.service.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
