server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  application:
    name: service-provider
  main:
      allow-bean-definition-overriding: true
mybatis:
  type-aliases-package: com.cloud.service.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
    instance:
      lease-expiration-duration-in-seconds: 10 # 10秒即过期,服务续约(renew)的间隔，默认为30秒
      lease-renewal-interval-in-seconds: 5 # 5秒一次心跳,服务失效时间，默认值90秒
